# Generated by Django 4.2.3 on 2023-07-23 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='student',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='app1.student'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='teacher',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='app1.teacher'),
        ),
    ]
