# Generated by Django 4.2.3 on 2023-07-23 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_announcement_student_announcement_teacher'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admin',
            new_name='Administrator',
        ),
    ]
